// Copy this file and name it "localconfig.inc"

// Tab note: This file looks best if you set the tab length to 8 characters

// MySQL connection details
#define MYSQL_LOGLEVEL		ERROR
#define MYSQL_HOST		"localhost"
#define MYSQL_USER		"root"
#define MYSQL_PASSWORD		""
#define MYSQL_DATABASE		"grgserver"

// URL serving files from the audio directory (The filename gets directly appended without any additional character)
#define AUDIO_URL		"http://audio.example.com/"