/*
	@Release Name: SHA512
	@Release Type: Plugin
	@Author: RyDeR`
	@Update: 10/11/2010 - 14:30
	@Credits: http://www.planetsourcecode.com/vb/scripts/ShowCode.asp?txtCodeId=12669&lngWId=3
	@Functions:
				@Function: SHA512(const string[], buffer[], len);
				@Info: Obvious.
				@Params:
						@string[] - The string you want to hash.
						@buffer[] - String variable to store the hashed data in.
						@len = Size of buffer.
*/

native SHA512(const string[], buffer[], len);